### Mock 502 from Nginx
GET http://localhost:10001/nginx-502

### Mock 503 response with CRLF
GET http://localhost:10001/nginx-503-crlf

### Raw json response
GET http://localhost:10001/raw-json-simple

### Request with Large Body
POST http://localhost:10001/non-exist-req

{
  "name": "John Doe",
  "username": "johndoe",
  "email": "john@example.com",
  "address": "irrelevant-address",
  "age": 30,
  "title": "Architect",
  "Hobit": "Coding"
}