@baseUrl = http://localhost:10001

### Mock 400 from Nginx
GET {{baseUrl}}/nginx-400

### Mock 502 from Nginx
GET {{baseUrl}}/nginx-502

### Mock 503 response with CRLF
GET {{baseUrl}}/nginx-503-crlf

### Raw json response
GET {{baseUrl}}/raw-json-simple

### Request with Large Body
POST {{baseUrl}}/non-exist-req

{
  "name": "John Doe",
  "username": "johndoe",
  "email": "john@example.com",
  "address": "irrelevant-address",
  "age": 30,
  "title": "Architect",
  "Hobit": "Coding"
}

### Make a long list below (more than 13 requests)
GET {{baseUrl}}/ping

### 002
GET {{baseUrl}}/ping

### 003
GET {{baseUrl}}/ping

### 004
GET {{baseUrl}}/ping

### 005
GET {{baseUrl}}/ping

### 006
GET {{baseUrl}}/ping

### 007
GET {{baseUrl}}/ping

### 008
GET {{baseUrl}}/ping

### 009
GET {{baseUrl}}/ping

### 010
GET {{baseUrl}}/ping
